/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "file.h"

bool_t
xdr_uint (XDR *xdrs, uint *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_b (XDR *xdrs, b *objp)
{
	register int32_t *buf;

	 if (!xdr_bool (xdrs, objp))
		 return FALSE;
	return TRUE;
}
